services:
  postgres:
    build:
      context: ../data
      dockerfile: dockerfile.postgres
    container_name: ssco-store-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpw
      POSTGRES_DB: ssco-store-testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "com.docker.compose.project=ssco-store-sdk"

volumes:
  postgres-data: